# Generated by Django 2.1 on 2018-10-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('cars gathering', 'Cars Gathering'), ('party', 'Party'), ('concert', 'Concert'), ('conference', 'Conference'), ('expo', 'Expo'), ('business', 'Business'), ('year end functions', 'Year End Functions'), ('seminars', 'Seminars'), ('product launches', 'Product Launches'), ('team building events', 'Team Building Events'), ('golf event', 'Golf Event'), ('vip event', 'Vip Event'), ('award ceremonies', 'Award Ceremonies')], default='cars gathering', max_length=50),
        ),
    ]
